FROM node:16 AS build

COPY . /origin

WORKDIR /origin

RUN npm ci && \
    npm run build

FROM node:16

WORKDIR /app

COPY --from=build /origin/dist /app/dist
COPY --from=build /origin/node_modules /app/node_modules

COPY ./.env /app/
COPY ./.env.production /app/

CMD node dist/main.js