FROM alpine AS ssl

WORKDIR /ssl/

RUN apt-get update && \
  openssl req -newkey rsa:4096 \
    -days 365 \
    -nodes \
    -x509 \
    -subj "/C=KR/ST=Seoul/L=Seoul/O=blog/OU=blog/CN=localhost" \
    -keyout private.key \
    -out certification.crt


FROM nginx:alpine

COPY ./nginx.conf /etc/nginx/nginx.conf
COPY --from=ssl /ssl/private.key /etc/ssl/
COPY --from=ssl /ssl/certification.crt /etc/ssl/

EXPOSE 443

CMD ["nginx", "-g", "daemon off;"]